app1/urls.py
from app1.views import *
from django.urls import path

app_name='something'

urlpatterns=[

    path('balaji/',balaji,name='balaji'),
]

app2/urls.py
from app2.views import *
from django.urls import path

app_name='nothing'

urlpatterns=[

    path('roshni/',roshni,name='roshni'),
]

balaji8/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def balaji(request):
    return render(request,'balaji.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def roshni(request):
    return render(request,'roshni.html')

templates/balaji.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>balaji</title>
</head>
<body>
    <center>
        <h1>Hii roshni how are you</h1>
        <h2>Today you are coming to institute</h2>
        <a href="{% url 'nothing:roshni' %}"><h1>see roshni response</h1></a>
    </center>
</body>
</html>

templates/roshni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>roshni</title>
</head>
<body>
    <center>
        <h1>Hlo balaji tell</h1>
        <h2>yes iam coming for institute and iam on the way</h2>
        <a href="{% url 'something:balaji' %}"><h1>see what balaji said</h1></a>
    </center>
</body>
</html>